apiVersion: v1
kind: List
items:
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "parksmap-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/dulecux/advdev_homework"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: ParksMap/Jenkinsfile
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "mlbparks-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/dulecux/advdev_homework"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: MLBParks/Jenkinsfile
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "nationalparks-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/dulecux/advdev_homework"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: NationalParks/Jenkinsfile
