apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sz-builds
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: builder
    name: builder
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: builder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /go-scratch/hello_world
      git:
        uri: https://github.com/tonykay/ose-chained-builds
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-go:latest
          namespace: 7667-builds
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: 9jejZknHBqbKNjlqtOPy
      type: GitHub
    - generic:
        secret: cE9Jy5KH9vaHMP-_X92r
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ola
    name: ola
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ola:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/wkulhanek/ola.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: n7BVQVejblbO67agcWmt
      type: GitHub
    - generic:
        secret: rncpdYIhT5DT7A6nfUMJ
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: ola-binary
    name: ola-binary
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ola-binary:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: y67Wpp9eQ_ZKHMe-hQy2
      type: GitHub
    - generic:
        secret: 9n5qadP4fXu7ZyCc0vwB
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: runtime
    name: runtime
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: runtime:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM scratch
        COPY main /main
        EXPOSE 8080
        ENTRYPOINT ["/main"]
      images:
      - from:
          kind: ImageStreamTag
          name: builder:latest
          namespace: 7667-builds
        paths:
        - destinationDir: .
          sourcePath: /opt/app-root/src/go/src/main/main
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: scratch
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: VyaER8Xuna-GIkR-rRrF
      type: GitHub
    - generic:
        secret: lytlaZ54cbttWs9FP4JZ
      type: Generic
    - imageChange:
        from:
          kind: ImageStreamTag
          name: builder:latest
          namespace: 7667-builds
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: tasks
      template: eap70-basic-s2i
      xpaas: 1.4.14
    name: tasks
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: tasks:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /
      git:
        ref: master
        uri: http://gogs-7667-gogs.apps.0845.openshift.opentlc.com/CICDLabs/openshift-tasks-private.git
      sourceSecret:
        name: gogs-secret
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: http://nexus3-7667-nexus.apps.0845.openshift.opentlc.com/repository/maven-all-public
        - name: ARTIFACT_DIR
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.7
          namespace: openshift
        incremental: true
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: KfdXh2QK
      type: GitHub
    - generic:
        secret: iW7OoVVL
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: my-application
    name: my-application
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: my-application
      deploymentconfig: my-application
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: my-application
          deploymentconfig: my-application
      spec:
        containers:
        - image: docker-registry.default.svc:5000/7667-builds/runtime@sha256:e3e9f6db0045739fa30ffb139f1dc7a51821b7d9a8e56174e79848beba772655
          imagePullPolicy: Always
          name: my-application
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - my-application
        from:
          kind: ImageStreamTag
          name: runtime:latest
          namespace: 7667-builds
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: ola
    name: ola
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ola
      deploymentconfig: ola
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ola
          deploymentconfig: ola
      spec:
        containers:
        - image: docker-registry.default.svc:5000/7667-builds/ola@sha256:7c91b4d68fe833f0c4d5e13e54cd1bf255fbe0f493316a682fd0ad83905c55d5
          imagePullPolicy: Always
          name: ola
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ola
        from:
          kind: ImageStreamTag
          name: ola:latest
          namespace: 7667-builds
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: ola-binary
    name: ola-binary
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ola-binary
      deploymentconfig: ola-binary
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ola-binary
          deploymentconfig: ola-binary
      spec:
        containers:
        - image: docker-registry.default.svc:5000/7667-builds/ola-binary@sha256:e982b78d510263842ad753a7d414635a6ac5c1909814ccc6205153b6fbf0d623
          imagePullPolicy: Always
          name: ola-binary
          ports:
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ola-binary
        from:
          kind: ImageStreamTag
          name: ola-binary:latest
          namespace: 7667-builds
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: eap70-basic-s2i
      application: tasks
      template: eap70-basic-s2i
      xpaas: 1.4.14
    name: tasks
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentConfig: tasks
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: eap70-basic-s2i
          application: tasks
          deploymentConfig: tasks
        name: tasks
      spec:
        containers:
        - env:
          - name: JGROUPS_PING_PROTOCOL
            value: openshift.DNS_PING
          - name: OPENSHIFT_DNS_PING_SERVICE_NAME
            value: tasks-ping
          - name: OPENSHIFT_DNS_PING_SERVICE_PORT
            value: "8888"
          - name: MQ_CLUSTER_PASSWORD
            value: tsEYNtWs
          - name: MQ_QUEUES
          - name: MQ_TOPICS
          - name: JGROUPS_CLUSTER_PASSWORD
            value: 8jVYyrd2
          - name: AUTO_DEPLOY_EXPLODED
            value: "false"
          image: docker-registry.default.svc:5000/7667-builds/tasks@sha256:ffaa93937c73280e2f9181eb9245175f96b75291f6e291bc996e31d025f1755f
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: tasks
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 75
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - tasks
        from:
          kind: ImageStreamTag
          name: tasks:latest
          namespace: 7667-builds
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: my-application
    name: my-application
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: my-application
      deploymentconfig: my-application
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ola
    name: ola
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: ola
      deploymentconfig: ola
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ola-binary
    name: ola-binary
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: ola-binary
      deploymentconfig: ola-binary
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: tasks
      template: eap70-basic-s2i
      xpaas: 1.4.14
    name: tasks
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: tasks
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The JGroups ping port for clustering.
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: tasks
      template: eap70-basic-s2i
      xpaas: 1.4.14
    name: tasks-ping
  spec:
    clusterIP: None
    ports:
    - name: ping
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      deploymentConfig: tasks
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: my-application
    name: my-application
  spec:
    host: my-application-7667-builds.apps.0845.openshift.opentlc.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: my-application
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-08-29T07:28:28Z
        status: "True"
        type: Admitted
      host: my-application-7667-builds.apps.0845.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: ola
    name: ola
  spec:
    host: ola-7667-builds.apps.0845.openshift.opentlc.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ola
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-08-29T04:58:11Z
        status: "True"
        type: Admitted
      host: ola-7667-builds.apps.0845.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: ola-binary
    name: ola-binary
  spec:
    host: ola-binary-7667-builds.apps.0845.openshift.opentlc.com
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ola-binary
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-08-29T07:05:21Z
        status: "True"
        type: Admitted
      host: ola-binary-7667-builds.apps.0845.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: tasks
      template: eap70-basic-s2i
      xpaas: 1.4.14
    name: tasks
  spec:
    host: tasks-7667-builds.apps.0845.openshift.opentlc.com
    to:
      kind: Service
      name: tasks
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-08-29T04:15:49Z
        status: "True"
        type: Admitted
      host: tasks-7667-builds.apps.0845.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
