apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sz-logging
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: logtofile
    name: logtofile
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: logtofile
      deploymentconfig: logtofile
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: logtofile
          deploymentconfig: logtofile
      spec:
        containers:
        - args:
          - /bin/sh
          - -c
          - sleep 5 && tail -n+1 -f /tmp/datelog.txt
          image: busybox
          imagePullPolicy: Always
          name: logging-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        - image: docker.io/wkulhanek/logtofile@sha256:11b85189e51e5ae8a94431df68021588a3d3baae9c7af3c87ab7478002035db9
          imagePullPolicy: Always
          name: logtofile
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: tmp
          persistentVolumeClaim:
            claimName: logs
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - logtofile
        from:
          kind: ImageStreamTag
          name: logtofile:latest
          namespace: 7667-logging
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
