apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sz-tasks-dev
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: tasks
    name: tasks
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: tasks:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.6
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: K-yeuod0NlHX0L6dvU_-
      type: GitHub
    - generic:
        secret: CuIKa-0ztEBvyy92sQX8
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: tasks
    name: tasks
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tasks
      deploymentconfig: tasks
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: tasks
          deploymentconfig: tasks
      spec:
        containers:
        - image: docker-registry.default.svc:5000/7667-tasks-dev/tasks:1.1-1
          imagePullPolicy: IfNotPresent
          name: tasks
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/eap/standalone/configuration/application-users.properties
            name: jboss-config
            subPath: application-users.properties
          - mountPath: /opt/eap/standalone/configuration/application-roles.properties
            name: jboss-config1
            subPath: application-roles.properties
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config1
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: tasks
    name: tasks
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: tasks
      deploymentconfig: tasks
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: tasks
    name: tasks
  spec:
    host: tasks-7667-tasks-dev.apps.0845.openshift.opentlc.com
    port:
      targetPort: 8080
    to:
      kind: Service
      name: tasks
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-08-29T08:12:29Z
        status: "True"
        type: Admitted
      host: tasks-7667-tasks-dev.apps.0845.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
