kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/dulecux/advdev_homework"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
       env:
         - name: GUID
           value: 89a4
         - name: CLUSTER
           value: na39.openshift.opentlc.com
       jenkinsfilePath: MLBParks/Jenkinsfile
