kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nationalparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/dulecux/advdev_homework.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Nationalparks/Jenkinsfile
