kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nationalparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/SammZhu/advdev_homework"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
       env:
         - name: GUID
           value: a7fd
         - name: CLUSTER
           value: na39.openshift.opentlc.com
       jenkinsfilePath: Nationalparks/Jenkinsfile
