kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "parksmap-pipeline"
spec:
  source:
    git:
      uri: "oc export all --as-template=[template-name].git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ParksMap/Jenkinsfile
